on: [push]
name: Debugger CI
jobs:
  build-vscode-extension:
    name: Build vscode-extension
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build extension
        run: |
          cd vscode-extension/
          nix-build

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: Extension Vsix
          path: vscode-extension/result/haskell-debugger-extension-0.1.0.vsix

  build-ghc-debugger:
    name: Build ghc-debug-adapter
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: latest-nightly
          cabal-version: latest
          ghcup-release-channel: https://ghc.gitlab.haskell.org/ghcup-metadata/ghcup-nightlies-0.0.7.yaml

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build ghc-debug-adapter
        run: cabal build exe:ghc-debug-adapter

      - name: Upload ghc-debug-adapter binary
        uses: actions/upload-artifact@v4
        with:
          name: ghc-debug-adapter
          path: dist-newstyle/build/*/*/ghc-debug-adapter/build/ghc-debug-adapter/ghc-debug-adapter


  test-ghc-debugger:
      name: Test ghc-debug-adapter
      runs-on: ubuntu-latest
      needs: build-ghc-debugger
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive

        - uses: haskell-actions/setup@v2
          with:
            ghc-version: latest-nightly
            cabal-version: latest
            ghcup-release-channel: https://ghc.gitlab.haskell.org/ghcup-metadata/ghcup-nightlies-0.0.7.yaml

        - uses: cachix/install-nix-action@v31
          with:
            nix_path: nixpkgs=channel:nixos-unstable

        - name: Download ghc-debug-adapter binary
          uses: actions/download-artifact@v4
          with:
            name: ghc-debug-adapter
            path: ./bin/

        - name: Run integration tests
          run: |
            cd test/integration-tests/
            make clean
            make build
            make test DEBUGGER=./bin/ghc-debug-adapter

